# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-13 08:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hoor.TorrentServer'),
        ),
    ]
