# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-27 12:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('minuto', models.CharField(default='*', max_length=20)),
                ('hora', models.CharField(default='*', max_length=20)),
                ('diames', models.CharField(default='*', max_length=20)),
                ('mes', models.CharField(default='*', max_length=20)),
                ('diasemana', models.CharField(default='*', max_length=20)),
                ('task', models.CharField(max_length=200)),
                ('descrip', models.CharField(default=models.CharField(max_length=200), max_length=200)),
                ('activo', models.NullBooleanField(default=False)),
                ('ultima', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tasks',
                'managed': True,
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
