# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-30 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='vista',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
