# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-30 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='vista',
            field=models.CharField(blank=True, default='NRS00E00', max_length=8, null=True),
        ),
    ]
