# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-28 09:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('merc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransmissionReceivers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transmission_active', models.NullBooleanField(default=False)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('fullname', models.CharField(blank=True, max_length=200, null=True)),
                ('group', models.CharField(blank=True, max_length=200, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transmissionreceivers_autor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transmissionreceivers',
                'managed': True,
                'verbose_name_plural': 'TransmissionReceivers',
            },
        ),
    ]
