# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-12 12:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merc', '0002_transmissionreceivers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramchatids',
            name='author',
        ),
    ]
