# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-30 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merc', '0002_series_vista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='vista',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
