# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-24 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merc', '0002_series_vista'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='ep_audi',
            field=models.CharField(blank=True, default='NRS00E00', max_length=8, null=True),
        ),
    ]
