# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-21 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=200)),
                ('ep_start', models.CharField(blank=True, db_column='EP_START', default='NRS00E00', max_length=8, null=True)),
                ('ep_end', models.CharField(blank=True, db_column='EP_END', default='NRS99E99', max_length=8, null=True)),
                ('quality', models.CharField(db_column='QUALITY', default='NR', max_length=2)),
                ('ultima', models.DateTimeField(auto_now_add=True, db_column='ULTIMA', null=True)),
                ('paussed', models.NullBooleanField(db_column='PAUSSED', default=False)),
                ('skipped', models.NullBooleanField(db_column='SKIPPED', default=False)),
            ],
            options={
                'db_table': 'SERIES',
                'managed': True,
                'verbose_name_plural': 'series',
            },
        ),
        migrations.CreateModel(
            name='TelegramChatIds',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('firstname', models.CharField(blank=True, max_length=200, null=True)),
                ('surname', models.CharField(blank=True, max_length=200, null=True)),
                ('group', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'telegram_chat_ids',
                'managed': True,
                'verbose_name_plural': 'telegram_chat_ids',
            },
        ),
        migrations.AlterUniqueTogether(
            name='series',
            unique_together=set([('nombre', 'quality')]),
        ),
    ]
