# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-29 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercurio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='genero',
        ),
        migrations.AddField(
            model_name='series',
            name='genero',
            field=models.ManyToManyField(to='mercurio.Genero'),
        ),
    ]
