# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-05 12:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Capitulos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('temporada', models.IntegerField()),
                ('capitulo', models.IntegerField()),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('visto', models.NullBooleanField(default=False)),
                ('descargado', models.NullBooleanField(default=False)),
            ],
            options={
                'managed': True,
                'verbose_name_plural': 'Capitulos',
            },
        ),
        migrations.CreateModel(
            name='Fichas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('estado', models.IntegerField(choices=[(0, 'Descartada'), (1, 'Activa'), (2, 'Pendiente de nueva Temporada'), (3, 'Cancelada'), (4, 'Terminada')], default='0')),
                ('imagen', models.CharField(default='generico.jpg', max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas_autor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'managed': True,
                'verbose_name_plural': 'fichas',
            },
        ),
        migrations.AddField(
            model_name='capitulos',
            name='ficha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hod.Fichas'),
        ),
        migrations.AlterUniqueTogether(
            name='fichas',
            unique_together=set([('nombre', 'author', 'estado')]),
        ),
        migrations.AlterUniqueTogether(
            name='capitulos',
            unique_together=set([('ficha', 'temporada', 'capitulo')]),
        ),
    ]
